apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: queue-func-secret
data:
  ConnString: <rabbitmq-connection-string>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-func-deployment
  labels:
    app: queue-func
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue-func
  template:
    metadata:
      labels:
        app: queue-func
    spec:
      containers:
      - name: queue-func
        image: learningdayacr.azurecr.io/rmq-func:v1
        envFrom:
        - secretRef:
            name: queue-func-secret
